spring:
  cloud:
    consul:
      discovery:
        ##检测实例健康
        health-check-path: /actuator/health
        ##每隔10s检查
        health-check-interval: 10s
        ##自动注册
        register: true
        ##实例名称
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
      #consul地址
      host: localhost
      port: 8500
      config:
        enabled: true
        ##配置中心解析样式
        format: yaml
  profiles:
    active: dev
  application:
    name: greed

## May produce "feign.RetryableException: Read timed out executing POST" without this config
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

server:
  port: 8889

call-class:
  map:
    E000: 大数据输出
    E001: 手机归属地
    E002: 地区生产总值


