logging:
  config: classpath:log4j2-dev.xml

com:
  kris:
    greed:
      # File Path
      filePath: /usr/local/excel/
      # Request Url
      url: http://localhost:8888

      mobileOperator:
        fileName: 手机号运营商
        sheetName: 手机号运营商
      dataDevelopment:
        fileName: prophecy调用量统计
        sheetName: 调用量统计
      domesticProduct:
        fileName: 全国各地区生产总值
        sheetName: 地区生产总值
      nationalPopulation:
        fileName: 全国各地区人口
        sheetName: 地区人口
      taobaoBeauty:
        fileName: 淘女郎列表
        sheetName: 淘女郎列表